[package]
name = "mayit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
may_minihttp = "0.1"
mongodb = "2.8"
futures = "0.3"
tokio = { version = "1.36.0", features = ["full"] }
